baseurl: "/jekyll-microbulma"
lang: es
author: Mario Abreu
title: Micro One!
subtitle: Made it with Bulma and ♥
twitter_user: maxito_abreu
github_user: max131

plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

permalink: "/post/:title/"    
paginate: 3
paginate_path: "/page/:num"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mario Abreu"
      
