baseurl: "/jekyll-microbulma"
lang: es
author: Mario Abreu
title: Jekyll & Bulma
subtitle: Made it with Bulma and ♥ 

plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# kramdown:
  # input: GFM

paginate: 3
paginate_path: "/page/:num"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mario Abreu"
  
